# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ImageUpload',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('bookid', models.IntegerField()),
            ],
            options={
                'db_table': 'UserRating',
            },
        ),
    ]
