# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender_app', '0002_remove_imageupload_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='bookid',
            new_name='book_id',
        ),
        migrations.AddField(
            model_name='userrating',
            name='user_id',
            field=models.IntegerField(default=60000),
        ),
    ]
